name: CI/CD Docker

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Gerar Docker tag
        id: vars
        run: |
          # Pega o SHA curto do commit
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          # Define a tag "latest" + commit
          echo "IMAGE_TAG_SHA=$SHORT_SHA" >> $GITHUB_ENV
          echo "IMAGE_TAG_LATEST=latest" >> $GITHUB_ENV
          echo "IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/pratica-devops-python" >> $GITHUB_ENV
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG_LATEST }}
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG_SHA }}
